# Generated by Django 3.1.7 on 2021-10-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=1)),
            ],
            options={
                'db_table': 'USER_INFORMATION_DATABASE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VaccinationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccineBrand', models.CharField(max_length=200)),
                ('patientKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'db_table': 'USER_VACCINATION_DATABASE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TextSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30000)),
                ('processedText', models.CharField(max_length=30000)),
                ('patientKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'db_table': 'USER_TEXTSYMTOMS_DATABASE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SymptomsPredicted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=200)),
                ('patientKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'db_table': 'USER_SYMTOMS_DATABASE',
                'managed': True,
            },
        ),
    ]
