# Generated by Django 3.1.7 on 2021-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211031_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdata',
            name='birthDefect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationdata',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationdata',
            name='numDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinationdata',
            name='numDoses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinationdata',
            name='numHosDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinationdata',
            name='visit',
            field=models.BooleanField(default=False),
        ),
    ]
