# Generated by Django 3.1.7 on 2021-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211111_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdata',
            name='lifeDesease',
            field=models.BooleanField(default=False),
        ),
    ]
