# Generated by Django 3.1.7 on 2021-11-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vaccinationdata_lifedesease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threshold',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='threshold',
            table='MODEL_THRESHOLD_DATABASE',
        ),
    ]
